# Generated by Django 5.0.7 on 2024-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="locality",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("MO", "Mondstadt"),
                    ("LI", "Liyue"),
                    ("IN", "Inazuma"),
                    ("SU", "Sumeru"),
                    ("FO", "Fontaine"),
                    ("OG", "Other Games"),
                ],
                max_length=2,
            ),
        ),
    ]
