# Generated by Django 5.0.7 on 2024-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_payment_order_orderplaced_delete_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AlterField(
            model_name="payment",
            name="paypal_order_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paypal_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paypal_payment_status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
